import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ToastComp from '@/components/toasts';
import StoreProvider from '@/providers/storeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ERP Aksata',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastComp />
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}